### ISSUE TITLE
Empty array in optional as a default value turns the type into union of the type or never

### ISSUE THREAD

**Issue by jansedlon** [fabian-hiller/valibot#593]
Given this schema

```ts
const ResourceSchema = variant("type", [
  object({
    type: literal("link"),
    url: pipe(string(), url()),
    label: pipe(string(), minLength(1)),
  }),
  object({
    type: literal("file"),
    filename: pipe(string(), minLength(1)),
    size: pipe(string(), minLength(1)),
    location: pipe(string(), userUploadValidation(true)),
    status: picklist(["uploading", "error", "done"]),
  }),
]);

export const CourseSectionSchema = object({
  title: pipe(string(), minLength(1)),
  content: string(),
  video: pipe(
    union([pipe(string(), url()), literal("")]),
    transform((val) => val || null),
  ),
  resources: optional(array(ResourceSchema), []),
});

export type CourseSectionSchemaData = InferOutput<typeof CourseSectionSchema>;
```

The `resources` type is inferred as never or the type. It shouldn't really be never. I'm on version 0.31

<img width="372" alt="image" src="https://github.com/fabian-hiller/valibot/assets/13948180/50cc0515-1937-4147-a721-005580fb3555">

**Comment by fabian-hiller** [comment]
Thank you for creating this issue, I will try to find a solution soon!

**Comment by fabian-hiller** [comment]
This should be fixed now! Thank you!

**Comment by jansedlon** [comment]
@fabian-hiller  Thank YOU for the wonderful work you're doing 🙏 One question, i updated the package and tried it again. Should it really infer to undefined if there's a provided default value?

<img width="346" alt="image" src="https://github.com/fabian-hiller/valibot/assets/13948180/7d77eebe-3435-48f1-9b97-818ed4b9c82b">

Why am i insisting on it so much? I'm using `@conform-to/react` library for Form handling in Remix.run framework and it returns available functions based on return type of a given schema. Since it infers the type as the type or undefined, I don't have access to array methods.

**Comment by fabian-hiller** [comment]
You are right, there is still a problem with empty arrays as default argument. I will fix it in the next few minutes and release another version. Thanks for your feedback!

**Comment by fabian-hiller** [comment]
Should be fixed now. You can check it in our [playground](https://valibot.dev/playground/?code=JYWwDg9gTgLgBAKjgQwM5wG5wGZQiOAcg2QBtgAjCGQgbgCh6BjCAO1XgGUmALAUxDI4AXkwA6CGBjA2ZABQYxyKFGQBPBRIoArPkxhyA3nADWfNQC5xHKMFYBzOQEo4AXydOANHADaAXScGehg1MD44AElWMABXeFFFKOw+KCjYmAAeELCIbDhufkEAPgZs8IB5OPSRcSSUyph0rNC+XPzeAWQSoA).

**Comment by jansedlon** [comment]
Works great, thank you
