### ISSUE TITLE
Website doesn't work from time to time

### ISSUE THREAD

**Issue by Perdolique** [fabian-hiller/valibot#751]
Hello. I'm having a problem with the documentation on https://valibot.dev. It opens slowly, or the connection is completely reset. I'm not sure what the problem is because some of my friends can open it from their network and some can't, like me.

**Comment by fabian-hiller** [comment]
I have never had any problems with it. I know some people have in the past. We host the site on Netlify's edge network. The only thing I could do is not host in on the edge network or choose another provider.

What you could do is use a VPN to access our site from another network or access it via a service like the Wayback Machine.

**Comment by Perdolique** [comment]
Yep, it works from one network and doesn't work from another.  I am not sure what the problem is, but at the moment the documentation is not accessible for me w/o VPN. It would be nice to have an alternative hosting or so. ¯\\(ツ)/¯

**Comment by fabian-hiller** [comment]
Another workaround is to clone the repo and run `pnpm i && cd website && pnpm start`. I will leave this open for now. If more people have this problem, I will try to contact Netlify or optionally offer to host the documentation on another domain hosted by another provider.

**Comment by fabian-hiller** [comment]
Our site seems to be stable for the last few months, but I will reopen if I am wrong.

**Comment by Perdolique** [comment]
Yep, it looks like only me is affected (just tried it 2 days ago). I've tried to open it from a couple of Estonian IP addresses and this side doesn't load at all. From VPN it does work. I can assume that the service under the documentation has problems with it. So, at the moment I'm using local build instead. Not so convenient, but works.

**Comment by fabian-hiller** [comment]
Hmm... thanks for your feedback. That's too bad. As soon as I have more time, I will publish it via Vercel and get back to you to see if that solves the problem.

**Comment by fabian-hiller** [comment]
I have received a response from Netlify:

If the site problem is only happening to certain users and disappears when they use a VPN, then the problem is likely something having to do with their local network or ISP. I'm afraid that isn't something Netlify will be able to help troubleshoot and is something they will need to contact their ISP or network admins to diagnose.
 
Still, we can try to look into it if someone can generate a HAR file demonstrating the issue.

**Comment by Perdolique** [comment]
TBH, I don't think this is an ISP problem because `valibot.dev` is loading from time to time, and the problem is only with this website at the moment. I've attached two HARs. One is when the website doesn't load at all (but it's just the default browser's timeout), and the second one is when it was loaded on the 10th try or so.

[HARs](https://drive.proton.me/urls/W2G8TX4XDW#eBljRVjqKEvp)

**Comment by fabian-hiller** [comment]
Thank you! I will forward it to Netlify.

**Comment by fabian-hiller** [comment]
Here is another answer from Netlify. But don't feel obligated to spend your time on it.

Unfortunately, the HAR file provided where the connection is unavailable doesn't provide any useful information to understand what's causing this issue. I'd recommend they attempt to connect from a different browser or different network to see if that produces different results.

**Comment by Perdolique** [comment]
In different browsers, the result will be the same, because the connection to `valibot.dev` just closed by timeout 9 out of 10 times. 🤷 I don't know exactly why, but the problem is only with this site. So I'm using local documentation at the moment.

**Comment by fabian-hiller** [comment]
This should be fixed

**Comment by Perdolique** [comment]
It still doesn't work in Estonia, but I'm using local version at the moment. I see the similar problem in Canada according to #918, so it looks like Netlify is poor service for use. Good to know at least. 😃

**Comment by fabian-hiller** [comment]
This is strange. The site has been hosted by Vercel since yesterday.

**Comment by Ky6uk** [comment]
> This is strange. The site has been hosted by Vercel since yesterday.

Yes, it's strange then. Maybe a kind of caching or so. I'll try next week once more I guess.
